### ISSUE TITLE
[RFC]: build a developer dashboard for tracking repository build status

### ISSUE THREAD

**Issue by the-r3aper7** [stdlib-js/google-summer-of-code#39]
# TABLE OF CONTENTS

- [Introduction](#introduction)
- [Goals](#goals)
  - [Roadmap to Status Dashboard](#roadmap-to-status-dashboard)
    - [Dashboard Designs](#here-are-some-designs-which-i-am-thinking-of-for-the-status-dashboard)
    - [Project Structure](#this-may-be-the-project-structure-for-our-frontend-part-of-the-website)
    - [Communication with APIs](#communication-with-apis)
    - [Implementation of REST API](#implementation-of-rest-api)
  - [Roadmap to Historical overviews and per package metrics.](#roadmap-to-historical-overviews-and-other-drill-down-metrics)
    - [Per Package Metrics Designs](#here-are-some-designs-which-i-am-thinking-of-for-the-metrics-page)
    - [Extending Frontend](#extending-frontend)
    - [Extending API](#extending-api)
  - [Project Documentation](#project-documentation)
- [Why this project?](#why-this-project)
- [Qualifications](#qualifications)
- [Commitment](#commitment)
- [Schedule](#schedule)

### Full name

Sai Srikar Dumpeti

### University status

Yes

### University name

Birla Institute of Technology, Mesra

### University program

Bachelor of Technology in Computer Science

### Expected graduation

2026

### Short biography

I am a 2nd year B.Tech. Student in the department of Computer Science and Technology at
Birla Institute of Technology, Mesra. I started my programming journey from 2019 in High School
i.e 12th Standard.
I am a self learnt programmer who likes to learn new things by creating new projects. Here are
some programming languages and frameworks which I have learn:
  
- Go
- Python
- JavaScript
- TypeScript
- Reactjs
- Svelte
- HTML/CSS
- Jest
- Stimulus

In College I have completed many courses like `Problem Solving with Programming in C`,
`Object Oriented Programming`, `Data Structure and Algorithms` and many more.
Currently attending courses of `Database Management Systems`, `Design Analysis of
Algorithms`, `Operating System`.
My Interests lie in `Web Development` and creating new things.

### Timezone

Asia/Kolkata UTC +0530

### Contact details

- **Email:** saisrikardumpeti@gmail.com 
- **GitHub:** https://github.com/the-r3aper7
- **Gitter:** https://matrix.to/#/@the-r3aper7:gitter.im

### Platform

Linux (Fedora)

### Editor

For development I use [Fedora](https://fedoraproject.org/) as Operating System and my editor is [VSCode](https://code.visualstudio.com/) because it is simple to use, learning curve is less and comes with lots build int features like [emmet](https://emmet.io/) features and extensions. However, I have learned basics of [vim](https://www.vim.org/) for working on servers.

### Programming experience

I have significant knowledge of programming, when I first started to learn programming in high school where I started my first language with `Python` I was fascinated by it. Afterwards I started to explore various fields but `Web Development` caught my interest. I have created some projects using `Django` Framework. Then, I started to learn `JavaScript` so that I can learn `React` for the front-end. Then I started contributing to `Open Source` to learn new things and it was great for exploration. I have learned a lot from `Open Source` and met a lot of amazing people.

### JavaScript experience

I've been having a great time learning JavaScript and working with it on front-end projects in open source environments. The best part about `JavaScript` is that you can literally build anything with it, from mobile apps with frameworks like [React Native](https://reactnative.dev) to web apps, games, and much more. Recently, I even came across a project where they built a whole operating system in the browser called [OS.js](https://www.os-js.org/)

Problems with JavaScript is that it has loose typing which can lead to problems if you don't use tools like `TypeScript` to add type safety. While `JSDoc` can help with documentation, it doesn't enforce types.However, there is a [RFC](https://github.com/tc39/proposal-type-annotations) going on where we can Static Types in `JavaScript` in Future. Another challenge is callback hell where nested callbacks can make code difficult to read and hard to maintain.

Here are some of my works with `JavaScript`:
- Checkout [my personal site](https://t27.vercel.app/) which I have created while I was learning `Svelte` [link to Repo](https://github.com/the-r3aper7/personal-site-v2).
- Checkout [Next.js file server](https://github.com/the-r3aper7/nextjs-file-server) which I have created while I was learning `Next.js`.
- Revamped the media page of [Qwik](https://qwik.dev) checkout the [PR](https://github.com/BuilderIO/qwik/pull/4970).
- Small Changes to Sidebar to [Qwik](https://qwik.dev/docs/getting-started/) checkout the [PR](https://qwik.dev/docs/getting-started/).
- Another Small Improvement in [Qwik's Media Page](https://qwik.dev/media/#blogs) checkout the [PR](https://github.com/BuilderIO/qwik/pull/4659).
- Here is a [website](https://achievechessacademy.com/) which I created for a client which was needed in 24hrs.

### Node.js experience

I haven't directly worked with `Node.js` yet, but I did leverage the API features of `Next.js v12` to create a file server interface for a local network. This project allowed for basic upload, download, and streaming functionalities. Check it out on GitHub here: [Nextjs File Server](https://github.com/the-r3aper7/nextjs-file-server.)

I'm definitely interested in getting more hands-on experience with `Node.js` in the future.

### C/Fortran experience

While I haven't had the chance to create a full project in C yet, I did take a course in `Programming for Problem Solving in C` during college. This course involved implementing basic algorithms in C, which provided a strong foundation in the language's core concepts.

### Interest in stdlib

While I am still developing my knowledge of statistics and machine learning algorithms, I have been impressed by the `stdlib-js/stdlib` library. It offers a collection of smaller, focused packages instead of a single, massive library that could bloat your bundle size. What particularly excites me is the ability to perform NumPy-like operations directly in the browser. The plotting API seems like a fantastic example of this functionality. I've also found the stdlib community to be very welcoming and approachable.

### Version control

Yes, Currently I am using Git as primary VCS.

### Contributions to stdlib

Here, are the statuses of some PR's which i have authored.

**Status Merged**

[All PRs which are merged](https://github.com/stdlib-js/stdlib/pulls?q=is%3Apr+is%3Aclosed+author%3Athe-r3aper7)

- [feat: added `utils/every-in-by`](https://github.com/stdlib-js/stdlib/pull/1409)
- [feat: add `math/base/special/acscd`](https://github.com/stdlib-js/stdlib/pull/1789)
- [feat: add `math/base/special/asecd`](https://github.com/stdlib-js/stdlib/pull/1788)
- [feat: add `math/base/special/secd`](https://github.com/stdlib-js/stdlib/pull/1787)
- [feat: add `math/base/special/cscd`](https://github.com/stdlib-js/stdlib/pull/1786)
- [feat: add `math/base/special/acotd`](https://github.com/stdlib-js/stdlib/pull/1785)
- [feat: add `math/base/special/atand`](https://github.com/stdlib-js/stdlib/pull/1784)
- [feat: add `math/base/special/acosd`](https://github.com/stdlib-js/stdlib/pull/1782)
- [feat: add `math/base/special/asind`](https://github.com/stdlib-js/stdlib/pull/1781)
- [feat: add `math/base/special/cotd`](https://github.com/stdlib-js/stdlib/pull/1772)
- [feat: add `math/base/special/tand`](https://github.com/stdlib-js/stdlib/pull/1771)
- [feat: add `math/base/special/cosd`](https://github.com/stdlib-js/stdlib/pull/1777)

**Status Opened**

[All Prs which are opened](https://github.com/stdlib-js/stdlib/pulls?q=is%3Apr+is%3Aopened+author%3Athe-r3aper7+)

- [docs(added readme examples for random/iter): added examples](https://github.com/stdlib-js/stdlib/pull/1769)

**Issues Opened**

[All issues which are currently opened](https://github.com/stdlib-js/stdlib/issues/created_by/the-r3aper7)

- none

### Goals

# Abstract

Stdlib is a Open Source Project written in `JavaScript`, Stdlib provides 3000+ high performance packages which can be used for numerical and scientific computation, statistics. Since, it is written in `JavaScript` we can used it any where some mobile via `react-native`, `Node.js` and `Browsers`. My proposal is to create a developer dashboard for tracking build status of those 3000+ repository. We may want to achieve this using `Reactjs` and `Fastify` for backend which will serve static files and API responses.

# Description for Project

For my completing my project I am going to divide it into 2 parts:

- Roadmap to Status Dashboard.
- Roadmap to Historical overviews and per package metrics.

Here are some libraries and tools which will be useful in this project.

- [Vitejs](https://vitejs.dev/) is a great build tool as it provides various features like `code-splitting`, `optimized builds` and `faster workflows`.
- [Reactjs](https://react.dev/) is a popular framework for building websites. Since we are in the initial stages we may not want to bloat the application with various technologies. Let's go simple and clear.
- [postgres](https://www.npmjs.com/package/postgres) we can use this library querying data from database directly in `JSON` format which we can be easily used for formatting and sending it to `frontend` for rendering.
- [Fastify](https://fastify.dev/) as the name suggests is fast and less overhead for creating REST API's. Fastify Ecosystem provides lots of plugins which will make DX easier and simpler. Since, we will be serving our react app from the same port as Fastify this will avoid the process of CORS.
- [Tape](https://github.com/tape-testing/tape) for testing the REST APIs and server.

## Roadmap to Status Dashboard
    
- ### Here are some designs which I am thinking of for the Status Dashboard.
  
  ### Index Page 
  ![Index Page](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/46eb9f8f-9bc3-4816-a564-af65ca1f5138)
  
  ### Index Page Explanation
  ![Index Page Explained](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/f426b6d8-c0a5-43a4-a847-a75248b52f2f)

  ### Index Page when filter button is clicked
  ![Property 1=Active Filter Button](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/42c347f7-11be-4b89-9c60-b45bf3daf2a5)

  ### Explanation
  ![Index Page Explained(3)](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/b1adc0b9-dd7d-48ef-8fb3-b15e6b4f71e5)

  ### Index Page when data is fetching
  ![Property 1=Loading Table Data](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/7f04a1fd-275f-44d0-9aa4-0cc9a1a6c4fb)

  ### Explanation
  ![Index Page Explained(1)](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/a6d512aa-0e17-4142-8647-aabe6885f650)

  ### Index Page when error occur in data fetching
  ![Property 1=Error while loading](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/3650e48f-40e2-4446-a9b2-36d4d017c269)

  ### Explanation
  ![Index Page Explained(2)](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/542477d7-4713-436a-9876-e7f05f1f2869)

  Links for the above designs:
  - [Prototype of the website](https://www.figma.com/proto/aenWqD5lmtYrIuvDTs0ctI/GSOC-2024?type=design&node-id=85-3559&t=fVELCnkPXzg3aRqH-1&scaling=contain&page-id=85%3A1943&mode=design)
  - [Designs of the website pages and instances](https://www.figma.com/file/aenWqD5lmtYrIuvDTs0ctI/GSOC-2024?type=design&node-id=0-1&mode=design)
  - [Designs of the website components](https://www.figma.com/file/aenWqD5lmtYrIuvDTs0ctI/GSOC-2024?type=design&node-id=75-5835&mode=design)
  - [Designs of the website table](https://www.figma.com/file/aenWqD5lmtYrIuvDTs0ctI/GSOC-2024?type=design&node-id=14-1833&mode=design)

- ### This may be the project structure for our frontend part of the website.

  ![Project Structure](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/b63a79ed-51f8-4ab7-a8fc-366c188ccc45)

  **Components**: from the above design we may use these components initially.

  - Table.jsx
  - Header.jsx
  - Chip.jsx
  - Icon.jsx
  - Card.jsx
  - Modal.jsx

  **Context**: Since, we are making it leaner and simple we may want to use Reactjs Context API to avoid prop drilling. We may store recently fetched data, search query and as project requirements while developing.
  
  **Constants**: we will store all constants like API urls that may be removed as per suggestion.

- ### Communication with APIs

  Since, we are seeking the project to be as simple as possible so we will use the Fetch API which is used by browsers natively for communication. We can create a Component for rendering table data.

  Checkout the example component which fetched the data from an API.
    
  > **NOTE!** This is a mockup component for the proposal that might change in the real project.
    
  Now, we easily render table data with changing urls and store the api response to a context as it would be easy to modify the data when a user clicks on `Sort Icon` as this would be deeply nested in the component tree.

- ### Implementation of REST API

  - **/** (_GET_): for serving the `index.html` file.
  - **/assets** (_GET_): for serving static files like css, js, svgs etc.
  - **/search** (_GET_): this route serves JSON data for a given query. Here are some search query parameters which it will take.
    - **q** _(required)_ _(type: string)_ for querying by the package-name.
      > Here, are some DX improving shortcuts to search.
      >
      > ### Basic Syntax will `[header cell/filter type]=[...]`
      > - if type is string then use `^`.
      > - if type is number then use `-`_(for range)_, `>=`, `>`, `<=`, `<`.
      >
      > 1) Initially when you type into search bar it will search for package which contains the package name in SQL which will look like this `select packagename from packages packagname like '%q%'` (**NOTE JUST A MOCK QUERY**).
      >
      > 2) Suppose you want to search for package.
      >     - Starts with given query you can type `name=^name-of-package`.
      >     - Ends with given query you can type `name=name-of-package^`.
      >     - if you type `name=name-of-package` this will be treated as default.
      >     - Examples: `name=^iter`
      >
      > 3) Suppose you want to filter your searches based on stars which is a number.
      >     - Range of star you can type `stars=1-10`
      >     - Less than a specific number you can type `stars=<10`
      >     - Greater than or Equal a specific number you can type `stars=<=10`
      >
      > 4) You can also combine multiple shortcut which is delimetered by ' ' (space) will look like this.
      >     - stars which ranges from 1 to 10, having `math` in their package name you can type something like `name=^math stars=1-10`.

    - **page** (_required_) (_type: integer_) which will be useful for pagination.
    - **size** (_required_) (_type: integer_) size of table rows which will render on client side.
    - **filters** (_required_) (_type: string delimetered by ","_)  we can use these serve only the data required by the client.

    #### Response Skeleton
    ```js
    {
      data: [
        {
          id: string, // useful for as key while mapping
          name: string,
          stars: number,
          status: string,
          license: string,
          lastModified: string,
          ... // add more to response as filters are applied
        }
        ...
      ],
      nextPage: string, // url with filters, size and q to next page.
      length: number, // current length of data.
    }
    ```
      
  - **/packages** (_GET_) this route will the table data.
    - **page** (_required_) (_type: integer_) which will be useful for pagination.
    - **size** (_required_) (_type: integer_) size of table rows which is currently selected.
    - **filters** (_required_) (_type: string delimetered by ","_) to serve only the data required by the client.
      
    #### Response Skeleton
    ```js
    {
      data: [
        {
          id: string, // useful for as key while mapping
          name: string,
          stars: number,
          status: string,
          license: string,
          lastModified: string,
          ... // add more to response as filters are applied
        }
        ...
      ],
      nextPage: string, // url with filters, size to next page.
      length: number, // current length of data.
    }
    ```

## Roadmap to Historical overviews and other drill down metrics.

- ### Here are some designs which I am thinking of for the metrics page.

  ### Overview Page when Downloads is selected.

  ![Overview Page](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/2c184179-f4f0-4964-be5b-507454bf9fc7)

  ### Overview Page Explained.
  
  ![Overview Page Explained](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/aa0e3f7c-0fc5-4e01-9696-9f41dcf8cc0e)
  
  ### Here are some Ideas for Other Metric like `Build Failures`.
  
  #### Only failures
  ![Build Failues only failures](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/81b77c27-44a9-4cda-8180-10d9d47ed54c)
  
  #### Only success
  ![Build Failures only success](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/1fc52cdf-b4bb-4350-9aa9-822c3357ba35)
  
  #### Fusion of Both
  ![Bulid Failures when both selected](https://github.com/stdlib-js/google-summer-of-code/assets/80447788/90fcb5b1-585d-46c9-9ae8-cb1947f067f6)

  Links for the above designs:
    - [Prototype of the website](https://www.figma.com/proto/aenWqD5lmtYrIuvDTs0ctI/GSOC-2024?type=design&node-id=128-3377&t=qeihihU4o5fcrG17-1&scaling=contain&page-id=85%3A1943&starting-point-node-id=128%3A3377&mode=design)

- ### Extending Frontend
  - Currently for demo purposes I have used [Lightweight Charts](https://tradingview.github.io/lightweight-charts/) library by [Trading View](https://www.tradingview.com/). 
  > NOTE! this may change as recommended by mentors in Community Bonding Period. 
  - Adding Polling to Status Dashboard with dropdown menu for selecting the time interval.

- ### Extending API
  - **/metrics/:package-id** (_GET_) which will take these search params.
    - **type** (_required_) (_type: string delimetered by ","_) this mean we can have `downloads`, `code coverage`, `build failures` and many more .

    ### Response Skeleton

    ```js
    {
      pkgName: string,
      githubURl: string,
      documentation: string,
      data: {
        downloads: [
          { date: string, value: number },
          ...
        ],
        codeCoverage: [
          { date: string, value: number },
          ...
        ],
        buildFailures: [
          { date: string, value: number },
          ...
        ]
        // add more data as defined in type
      },
    }
    ```

## Project Documentation

To ensure the codebase remains well-documented, I plan to document it with each pull request (PR) I submit. This way, the documentation burden stays manageable, especially as deadlines approach. Specifically, I will focus on documenting the changes I introduce in each PR, keeping the overall documentation up-to-date without requiring a separate, time-consuming documentation task.

### Why this project?

I am particularly interested in this project because it allows me to use my skills to create a tool that will positively affect the community. Best part of this, I can apply the frontend development skills I have learned through contributions to various open-source projects, along with my experience creating and working with APIs. This project presents a fantastic opportunity to use my knowledge and experience to work on something.

With the help of the developer dashboard, we can quickly view which packages have problems in their build status. This allows us to address issues for specific packages easily. Without the dashboard, you would have to go to every single package repository to check their build statuses. By using the dashboard, we can navigate and work more efficiently.

### Qualifications

I've made significant contributions to several well-respected frameworks. Here are some highlights:
- [Qwik's website](https://qwik.dev/) a frontend framework which introduced `Resumability` to frontend world.
  - I helped enhance the user experience of Qwik's website by redesigning the [Media Page](https://qwik.dev/media) 
  - I'm also nearing completion on the development of the [package manager tabs](https://github.com/BuilderIO/qwik/pull/5649) which will be integrated into production soon.
- [Wagtail](https://wagtail.org/)
  - Implementing a production-ready [url generator copy button](https://github.com/wagtail/wagtail/pull/11317) using [stimulusjs](https://stimulus.hotwired.dev/)
  - Migration of components from vanillajs to [stimulusjs](https://stimulus.hotwired.dev/) here are some migrations [enableDirtyFormCheck](https://github.com/wagtail/wagtail/pull/11373) and [tabs.js](https://github.com/wagtail/wagtail/pull/11542)

In addition to my open-source experience, I'm currently enrolled in a `Database Management System (DBMS)` course at college. This course is equipping me with the skills to execute queries efficiently and apply optimization techniques, which I'm eager to leverage in this project.

### Prior art

Yes, there is similar project like this from [npm](https://npm.github.io/statusboard/) where they are also tracking the build status, total downloads and many more things. From what I have understand from their [Github Repo](https://github.com/npm/statusboard)

They have created a folder named `workspaces` which contains 2 projects
- `www` from here they are serving simple **HTML**, **CSS**, **JS** and using [jquery](https://jquery.com/) for DOM manipulation.
- `data` from here they are serving their content from REST service or [GraphQL](https://graphql.org/) as needed.

All these things are automated by using GitHub Actions.

### Commitment

I plan on devoting my entire summer to this. I won't have any other kind of job, so I will be able to work a standard 40 hour week for the coding period. Also, my classes will end well before the coding period begins and will not start up again until well after the pencils down date, so I will be totally free for the whole period.

### Schedule

**Weeks 1: Community Bonding & Planning**
  - Activities:
    - Finalize frontend design with mentors (including user interface (UI) mockups or wireframes).
    - Discuss and document API routes and website theme.
    - Set up the development environment (including database setup if needed).
  - Deliverables:
    - Approved UI mockups/wireframes.
    - Documented API routes and website theme.
    - Development environment configured (including database setup, if applicable).

**Weeks 2-4: Frontend Development & Core Functionality (Roadmap to Status Dashboard)**
  - Activities:
    - Implement core frontend components with clear and concise code.
    - Thoroughly document components with comments and per-PR documentation.
    - Integrate front-end with APIs (if possible at this stage).
  - Deliverables:
    - Functional frontend components.
    - Well-documented code with per-PR documentation.
    - (Optional) Initial frontend-API integration.

**Weeks 5-7: Midterm and Per Package metrics (Roadmap to Historical overviews and per package metrics)**
  - Activities:
    - Conduct a mid-term review with mentors to assess progress and address any concerns.
    - Start working on the Package Overview page.
    - Continue documenting code throughout development.
  - Deliverables:
    - Fully functional website with core functionality.
    - Functional Package Overview page.
    - Ongoing code documentation.

**Week 8: Performance Optimization**
  - Activities:
    - Analyze and optimize database queries using the Postgres library.
    - Consider performance optimization techniques for the frontend (e.g., caching, lazy loading).
  - Deliverables:
    - Optimized database queries.
    - Improved frontend performance (if applicable).

**Weeks 9-11: Testing & Refinement**
  - Activities:
    - Write tests for APIs using `Tape`.
    - Fix any bugs identified during testing.
    - Continue with code documentation.
  - Deliverables:
    - Comprehensive unit tests for APIs.
    - Bug-free website.
    - Well-documented codebase.

**Week 12: Finalization & Review**
  - Activities:
    - Conduct a final review with mentors to ensure project completion aligns with initial goals.
    - Document any remaining parts of the codebase.
    - Prepare for presentation or deployment (if applicable).
  - Deliverables:
    - Project reviewed and approved by mentors.
    - Fully documented codebase.
    - Project ready for presentation or deployment.

Notes:

- The community bonding period is a 3 week period built into GSoC to help you get to know the project community and participate in project discussion. This is an opportunity for you to setup your local development environment, learn how the project's source control works, refine your project plan, read any necessary documentation, and otherwise prepare to execute on your project project proposal.
- Usually, even week 1 deliverables include some code.
- By week 6, you need enough done at this point for your mentor to evaluate your progress and pass you. Usually, you want to be a bit more than halfway done.
- By week 11, you may want to "code freeze" and focus on completing any tests and/or documentation.
- During the final week, you'll be submitting your project.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have read and understood the application materials found in this repository.
- [x] I have read and understood the [patch requirement](https://github.com/stdlib-js/google-summer-of-code/blob/main/README.md#patch-requirement) which is necessary for my application to be considered for acceptance.
- [X] The issue name begins with `[RFC]:` and succinctly describes your proposal.
- [X] I understand that, in order to apply to be a GSoC contributor, I must submit my final application to <https://summerofcode.withgoogle.com/> **before** the submission deadline.

**Comment by the-r3aper7** [comment]
> Hi @the-r3aper7 suggestions that you may incorporate in your proposal
> * Please link websites created by you in `Javascript Experience` section
> * In version control please state which version control you have worked with
> * How are planning to fetch data and render on dashboard you create?
> 
> How about linking a prototype wireframe to this? This will make things more clear. This is good. Thanks for your interest, looking forward to your contribution. 

Thanks @Pranavchiku will implement those suggestions.

**Comment by kgryte** [comment]
A few comments:

1. How will the table header cell UI element for ordering work? Do you plan to have it work over all table elements or just those displayed?
2. How will search work? What if I want to search for, say, all repos whose most recent builds are failing? Or which repos have >10 stars? And what if I want to "filter" for, say, all repos having names containing the substring "iter"?
3. You've chosen to use pagination rather than infinite virtual scrolling. Can you describe why?
4. Can you describe a bit more, in your own words, the need for this developer dashboard? What problem is trying to solve? Why is creating this dashboard important to the community?
5. Currently, the website is implemented with React using class components. You've chosen, in your code snippets, to use hooks. Was this intentional? If so, why?

**Comment by the-r3aper7** [comment]
1) So What I was thinking was to store a object in context provider like this `{key: 'name(default)', orderBy: 'ascending'}`.
whenever user clicks on header cell this change the `key` in context and we will use `memoize` to sort the data accordingly or `create a api route` if performance degrades, and now we can render the data which we have fetched initially which has been sorted. That's why I have chosen `pagination` over `infinite scroll`. Problem with infinite scroll will be reordering the elements when the fetched data becomes huge and this will degrade the performance of the website. 

2) No, I have not think in such a way I mean could be nice implementation for search let me think design for this.

3) explained above

4) With the help of developer dashboard we quickly view which package is having problem in building such that we can quickly address the problem for that specific package easily and without the dashboard you will have to go to every single package repository to check there build statuses and all by using this we have a easy time navigating and working more efficiently.

5) It was not purely intentional as I have seen in [react.dev](https://react.dev/reference/react/Component) says "Class components are still supported by React, but we don’t recommend using them in new code." Although I have just shared how data fetching will work. If we are opting in for `Class Based Components` it's fine. I will update the code if you want but with `functional based components` we will can leverage more code reuse-ability, read-ability and can have more concise and maintainable code and `React's` Team also **RECOMMENDED** it. I means it purely independent of what we choose, however we will achieve same the results.

**Comment by kgryte** [comment]
A few follow-up comments:

1. Developers are not likely to need to view this on mobile devices, so I don't think that needs to be emphasized or even pursued. We should assume that the 99% use case will be stdlib devs viewing the dashboard from their desktops.
2. You may want to peruse the code at https://github.com/stdlib-js/www/tree/master/lib/server, which implements a fastify server for serving our API documentation. It may be beneficial for understanding how we'd prefer the server code be organized.

**Comment by kgryte** [comment]
Also, do you have mock-ups for displaying drill down metrics on a per-package basis?

**Comment by steff456** [comment]
Hi @the-r3aper7, I just have one additional question:

1. Status graphs views are going to be created only for the selected package?

**Comment by the-r3aper7** [comment]
> Hi @the-r3aper7, thanks for opening this draft proposal. I just have one additional question:
> 
> 1. Status graphs views are going to be created only for the selected package? 

Yes as of now I thought graphs views are for the selected package.
